# Generated by Django 5.2.4 on 2025-07-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product__name'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
